# Copyright (c) 2026 Álvaro Cabrero Barros. Licensed under the MIT License. See LICENSE in the repository root.
"""Creates the project's horde config data assets.

Data assets are binary, so they cannot be written by hand. This script builds them with the editor's
Python API and is meant to be run without opening the editor window:

    UnrealEditor-Cmd.exe <path>\\HordeKiller.uproject -run=pythonscript -script=<path>\\Tools\\create_horde_configs.py

It is safe to run again: assets that already exist are left untouched, so values edited in the editor
are never overwritten. The game module must be compiled first, and the enemy Blueprint must exist
(see create_blueprints.py).
"""

import unreal

ENEMY_BLUEPRINT = "/Game/Blueprints/Characters/BP_HKEnemy"
FOLDER = "/Game/Data/Hordes"

# One entry per asset. "waves" is a list of waves; each wave is a list of (enemy asset path, count).
HORDES = [
    {
        # The horde the game plays by default: one wave of 6 that repeats forever, 4 enemies larger
        # each time (6, 10, 14, 18...).
        "name": "DA_HKHorde_Default",
        "waves": [[(ENEMY_BLUEPRINT, 6)]],
        "time_between_waves": 3.0,
        "endless": True,
        "endless_enemies_added_per_wave": 4,
        "spawn_radius_min": 1500.0,
        "spawn_radius_max": 2500.0,
    },
]


def load_enemy_class(asset_path):
    """Returns the class generated by an enemy Blueprint, or None if the Blueprint does not exist."""
    # The class of a Blueprint is a separate object named after the asset with a "_C" suffix.
    name = asset_path.rsplit("/", 1)[-1]
    return unreal.load_class(None, "{}.{}_C".format(asset_path, name))


def build_wave(groups):
    """Builds one FHKWaveConfig from a list of (enemy asset path, count)."""
    enemy_groups = []
    for asset_path, count in groups:
        enemy_class = load_enemy_class(asset_path)
        if enemy_class is None:
            unreal.log_warning("HKHordes: enemy {} not found; the group will use the basic enemy".format(asset_path))
        group = unreal.HKWaveEnemyGroup()
        group.set_editor_property("enemy_class", enemy_class)
        group.set_editor_property("count", count)
        enemy_groups.append(group)

    wave = unreal.HKWaveConfig()
    wave.set_editor_property("enemy_groups", enemy_groups)
    return wave


def create_horde(spec):
    """Creates one horde config asset and saves it. Returns True on success."""
    asset_path = "{}/{}".format(FOLDER, spec["name"])

    if unreal.EditorAssetLibrary.does_asset_exist(asset_path):
        unreal.log("HKHordes: {} already exists, skipped".format(asset_path))
        return True

    # The factory is what the editor uses for "New Data Asset"; it needs to know which class to create.
    factory = unreal.DataAssetFactory()
    factory.set_editor_property("data_asset_class", unreal.HKHordeConfig)

    asset = unreal.AssetToolsHelpers.get_asset_tools().create_asset(spec["name"], FOLDER, unreal.HKHordeConfig, factory)
    if asset is None:
        unreal.log_error("HKHordes: could not create {}".format(asset_path))
        return False

    asset.set_editor_property("waves", [build_wave(groups) for groups in spec["waves"]])
    asset.set_editor_property("time_between_waves", spec["time_between_waves"])
    asset.set_editor_property("endless", spec["endless"])
    asset.set_editor_property("endless_enemies_added_per_wave", spec["endless_enemies_added_per_wave"])
    asset.set_editor_property("spawn_radius_min", spec["spawn_radius_min"])
    asset.set_editor_property("spawn_radius_max", spec["spawn_radius_max"])

    # Assets created from script only exist in memory until they are saved.
    if not unreal.EditorAssetLibrary.save_loaded_asset(asset):
        unreal.log_error("HKHordes: could not save {}".format(asset_path))
        return False

    unreal.log("HKHordes: created {} with {} wave(s)".format(asset_path, len(spec["waves"])))
    return True


def main():
    results = [create_horde(spec) for spec in HORDES]
    unreal.log("HKHordes: finished, {} of {} ok".format(sum(results), len(results)))


main()
